steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -t, 'europe-west1-docker.pkg.dev/$PROJECT_ID/retrofit/app:$BUILD_ID', .]
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/retrofit/app:$BUILD_ID'
options:
  logging: CLOUD_LOGGING_ONLY
