export const REVIEWED_AT = '2026-09-09';
export const RULE_VERSION = '2026.09.10-2';
const base = 'https://www.seai.ie/grants/home-energy-grants/individual-grants/';
export const sourceCatalog = [
  {key:'ahb-oss',reviewedAt:'2026-09-11',title:'AHB One Stop Shop grants and registration',url:'https://www.seai.ie/grants/home-energy-grants/one-stop-shop/approved-housing-body',summary:'Registered Approved Housing Bodies use a separate OSS grant schedule. Valid AHBRA registration and confirmation of AHB ownership are required. AHB OSS attic grants detached/semi/mid-terrace/apartment: 2500/1900/1800/1400 euros; cavity: 2300/1700/1100/900; external: 10000/8000/4500/3500; heat pump systems: houses 6500, apartments 5500; mechanical ventilation 2000. These rates are not BEH rates. Tenants do not personally qualify as AHB applicants.'},
  {key:'beh-ahb',reviewedAt:'2026-09-11',title:'BEH applicant authorisation for AHBs',url:'https://www.seai.ie/grants/home-energy-grants/individual-grants/support-for-individual-grants',summary:'AHBs applying for Better Energy Homes must complete section 1 of the authorisation form and obtain approval before submitting applications. Do not transfer enhanced OSS AHB rates to BEH. An OSS can also manage BEH applications with upfront grant deduction; this does not change the funding scheme.'},
  {key:'hea',reviewedAt:'2026-09-11',title:'Home Energy Assessment grant',url:'https://www.seai.ie/grants/home-energy-grants/one-stop-shop/home-energy-assessments',summary:'SEAI provides a conditional €350 Home Energy Assessment grant through a registered One Stop Shop, once per property. The OSS deducts approved support upfront. Assessment fees vary; obtain quotes. SEAI example €600 less €350 = €250 is not a median. The homeowner may receive the assessment grant without proceeding with upgrades and may take the report to another OSS. Do not confuse an HEA with a standard BER or duplicate fees and grants in package totals.'},
  {key:'ber-scale',reviewedAt:'2026-09-11',title:'BER scale from 24 May 2026',url:'https://www.seai.ie/ber/new-simplified-scale',summary:'From 24 May 2026 the scale is A0, A, B, C, D, E, F, G. Existing certificates remain valid for ten years and must be preserved as issued. SEAI sample certificate shows primary-energy thresholds kWh/m2/year: A0 <=42 with ZEB criteria; A <=75; B <=150; C <=225; D <=275; E <=325; F <=375; G >375. Source: https://www.seai.ie/sites/default/files/2026-03/sample-new-ber-certificate.pdf. A0 is not established by energy alone. Relabelling is not a retrofit saving. The primary-energy assessment methodology also changed, so do not automatically convert a legacy certificate.'},
  {key:'ber-method',reviewedAt:'2026-09-11',title:'DEAP assessment methodology and 2026 changes',url:'https://www.seai.ie/ber/support-for-ber-assessors/deap',summary:'DEAP is the official dwelling energy assessment method. Updated primary-energy and CO2-equivalent factors and methodology apply from 24 May 2026. A BER primary-energy figure uses standard assessment conditions and is not household billed or final energy. Certificate headline values alone do not reproduce a DEAP assessment. Pathfinder sensitivity factors are explicit prototype assumptions, not SEAI calculations; qualified assessment must confirm outcomes.'},
  {key:'ber-fabric',reviewedAt:'2026-09-11',title:'What affects a dwelling BER',url:'https://www.seai.ie/ber/understand-a-ber-rating',summary:'BER depends on building fabric, ventilation, heating, lighting and renewables, with assessor evidence and standardised assumptions. SEAI explains that poorly insulated walls and roofs are important heat-loss paths. Heat-loss shares are not percentages of total BER energy saved by an upgrade and cannot be directly subtracted from a BER. A site assessment and suitable specifications are needed for a dependable post-works rating.'},
  {key:'oss',reviewedAt:'2026-09-10',title:'One Stop Shop funding and cost evidence',url:'https://www.seai.ie/grants/home-energy-grants/one-stop-shop/multiple-energy-upgrades',summary:'OSS: built and occupied before 2011; achieve minimum post-works BER B plus a heat pump or 100 kWh/m2/year primary-energy improvement. Approved grants deducted upfront by the OSS. Prior grants and energy credits need checking. SEAI linked 2025 dataset of 1,406 homes: detached works/grant/homeowner medians EUR 69,795/24,500/45,067; semi/end terrace 60,805/21,700/38,932; mid terrace 55,250/18,813/37,266; apartment 30,345/11,300/20,235. These independently calculated medians do not subtract. Historical data is not a quotation. Cost PDF: https://www.seai.ie/sites/default/files/grants/home-energy-grants/one-stop-shop/SEAI-OSS-Median-Costs-and-Grants.pdf'},
  {key:'funded',reviewedAt:'2026-09-10',title:'Fully Funded Energy Upgrades eligibility',url:'https://www.seai.ie/grants/home-energy-grants/fully-funded-upgrades-for-certain-homeowners',summary:'Warmer Homes: own and occupy, built and occupied before 2006, qualifying payment and suitable survey scope. Fuel Allowance, Working Family Payment, One-Parent Family Payment and Domiciliary Care Allowance qualify. Jobseekers or Disability Allowance require over six months and a child under seven. Carers Allowance requires living with the person cared for. SEAI verifies with DSP. Apartment management consent required. Survey-selected approved works are free, not every requested measure. Previous upgrades require review. No cash award to the homeowner.'},
  {key:'costs',reviewedAt:'2026-09-10',title:'Individual upgrades: historical cost evidence',url:'https://www.seai.ie/grants/home-energy-grants/individual-grants',summary:'Individual grants support separate measures; approval before starting works. The linked cost PDF covers 47,067 upgrades completed January–December 2025. Historical grant columns must not replace current grant rules. Apartment external-wall data contains six applications. The app uses published dwelling-type medians and explicitly assumed plus/minus 20 percent planning ranges, not SEAI confidence intervals. PDF: https://www.seai.ie/sites/default/files/publications/Median-costs-of-individual-energy-upgrades.pdf'},
  { key:'attic', title:'Attic insulation grants', url:base+'attic-insulation', summary:'Standard attic grants: detached EUR 2,000; semi-detached/end-terrace EUR 1,500; mid-terrace EUR 1,400. Homes must be built and occupied before 2011, have an MPRN and no previous attic grant. Higher grants exist for eligible first-time buyers and qualifying welfare recipients. Grant approval is required before works. Registered contractors and a post-works BER are required.' },
  { key:'walls', title:'Wall insulation grants', url:base+'wall-insulation', summary:'Cavity grants: detached EUR 1,800; semi-detached/end-terrace EUR 1,300; mid-terrace EUR 850. External wall grants: EUR 8,000 / 6,000 / 3,500 respectively. All external walls must be insulated. Survey suitability and building regulation requirements first. Earlier cavity or internal grants can permit specified supplementary upgrades. Confirm the complete scheme conditions.' },
  { key:'heat', title:'Heat pump system grants', url:base+'heat-pump-systems', summary:'Houses built and occupied before 2021 may qualify for up to EUR 12,500: system EUR 6,500, required central heating upgrades up to EUR 2,000, and eligible fossil-fuel or storage-heating replacement bonus EUR 4,000. Low heat loss is required. Pre-2007 homes normally require a technical assessment before application; check current exceptions. A BER label alone is not proof of suitability. Technical-assessment support is conditional.' },
  { key:'solar', title:'Solar electricity grants', url:base+'solar-electricity-grant', summary:'Solar PV: EUR 700 per kWp for the first 2 kWp plus EUR 200 per kWp up to 4 kWp, maximum EUR 1,800 in 2026. The home must be built and occupied before 2021, have an MPRN and no previous PV grant. Obtain grant approval first; assess roof condition, electrical connection and generation. A post-works BER is required.' }
];
export const sampleHomes = [
  { name:'My Dublin home', county:'Dublin', type:'semi', year:1985, area:115, ber:'D2', heating:'gas', walls:'cavity', attic:'partial', damp:'unknown', ventilation:'unknown', budget:45000, goal:'balanced', priorGrants:'none', applicantType:'private',ahbRegistered:'unknown',ownership:'owner', mprn:'yes', occupiedYear:1985, consent:false, traditional:'no', evidence:[], synthetic:true },
  { name:'The West Cork cottage', county:'Cork', type:'detached', year:1920, area:85, ber:'G', heating:'oil', walls:'solid', attic:'none', damp:'yes', ventilation:'unknown', budget:30000, goal:'comfort', priorGrants:'unknown', ownership:'owner', mprn:'yes', occupiedYear:1920, consent:false, traditional:'yes', evidence:[], synthetic:true }
];
